
---

# `environment.yml`

```yaml
name: eng-maths-agent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - networkx
  - jupyter
  - pytest
